# Generated by Django 5.1.3 on 2024-12-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0006_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(max_length=255),
        ),
    ]
