# Generated by Django 5.1.3 on 2024-12-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0007_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
